version: '3.5'
services:
  postgres: # Banco de dados
    image: docker.io/postgres
    command: 'postgres -c synchronous_commit=off -c shared_buffers=640MB -c max_connections=330 -c effective_cache_size=1GB -c maintenance_work_mem=384MB'
    environment:
      - POSTGRES_PASSWORD=connor
      - POSTGRES_USER=sarah
      - POSTGRES_DB=mydatabase
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
